# Eat Safe, Love

## Notebook Set Up

In [98]:
# Import dependencies
from pymongo import MongoClient
from pprint import pprint

In [99]:
# Create an instance of MongoClient
mongo = MongoClient(port=27017)

In [100]:
# assign the uk_food database to a variable name
db = mongo['uk_food']

In [101]:
# review the collections in our database
print(db.list_collection_names())

['food']

In [102]:
# assign the collection to a variable
food = db['food']

## Part 3: Exploratory Analysis
Unless otherwise stated, for each question: 
* Use `count_documents` to display the number of documents contained in the result.
* Display the first document in the results using `pprint`.
* Convert the result to a Pandas DataFrame, print the number of rows in the DataFrame, and display the first 10 rows.

### 1. Which establishments have a hygiene score equal to 20?

In [103]:
import pprint

# Find the establishments with a hygiene score of 20
query = {'scores.Hygiene': 20}
field = {'BusinessName': 1, 'scores': 1, '_id': 0}
hygiene = db.food.find(query, field)
hygiene_list = []
# Iterate over the cursor and print each document
for document in hygiene:
    pprint.pprint(document)
    hygiene_list.append(document)

{'BusinessName': 'The Chase Rest Home',
 'scores': {'ConfidenceInManagement': 20, 'Hygiene': 20, 'Structural': 20}}
{'BusinessName': 'Brenalwood',
 'scores': {'ConfidenceInManagement': 30, 'Hygiene': 20, 'Structural': 15}}
{'BusinessName': 'Melrose Hotel',
 'scores': {'ConfidenceInManagement': 20, 'Hygiene': 20, 'Structural': 20}}
{'BusinessName': 'Seaford Pizza',
 'scores': {'ConfidenceInManagement': 20, 'Hygiene': 20, 'Structural': 10}}
{'BusinessName': 'Golden Palace',
 'scores': {'ConfidenceInManagement': 20, 'Hygiene': 20, 'Structural': 10}}
{'BusinessName': "Ashby's Butchers",
 'scores': {'ConfidenceInManagement': 20, 'Hygiene': 20, 'Structural': 20}}
{'BusinessName': 'South Sea Express Cuisine',
 'scores': {'ConfidenceInManagement': 20, 'Hygiene': 20, 'Structural': 20}}
{'BusinessName': 'Golden Palace',
 'scores': {'ConfidenceInManagement': 30, 'Hygiene': 20, 'Structural': 15}}
{'BusinessName': 'The Tulip Tree',
 'scores': {'ConfidenceInManagement': 20, 'Hygiene': 20, 'Structural': 5}}
{'BusinessName': 'F & S',
 'scores': {'ConfidenceInManagement': 20, 'Hygiene': 20, 'Structural': 20}}
{'BusinessName': 'Longhouse',
 'scores': {'ConfidenceInManagement': 30, 'Hygiene': 20, 'Structural': 25}}
{'BusinessName': 'Westview Playgroup Based At Downsview Comm Primary',
 'scores': {'ConfidenceInManagement': 5, 'Hygiene': 20, 'Structural': 20}}
{'BusinessName': 'Whatever The Weather Coffee',
 'scores': {'ConfidenceInManagement': 20, 'Hygiene': 20, 'Structural': 15}}
{'BusinessName': 'Kings Restaurant (Oriental)',
 'scores': {'ConfidenceInManagement': 20, 'Hygiene': 20, 'Structural': 25}}
{'BusinessName': 'Xich Lo',
 'scores': {'ConfidenceInManagement': 10, 'Hygiene': 20, 'Structural': 5}}
{'BusinessName': 'Asian Supermarket Ltd: T/A Best Food Wine Ltd',
 'scores': {'ConfidenceInManagement': 20, 'Hygiene': 20, 'Structural': 20}}
{'BusinessName': 'Londis',
 'scores': {'ConfidenceInManagement': 30, 'Hygiene': 20, 'Structural': 10}}
{'BusinessName': 'Costcutter',
 'scores': {'ConfidenceInManagement': 20, 'Hygiene': 20, 'Structural': 15}}
{'BusinessName': 'La Simon Ltd',
 'scores': {'ConfidenceInManagement': 5, 'Hygiene': 20, 'Structural': 15}}
{'BusinessName': 'Caribiscus Ltd',
 'scores': {'ConfidenceInManagement': 30, 'Hygiene': 20, 'Structural': 20}}
{'BusinessName': 'Kennedy Fried Chicken',
 'scores': {'ConfidenceInManagement': 30, 'Hygiene': 20, 'Structural': 20}}
{'BusinessName': 'Gah Shing',
 'scores': {'ConfidenceInManagement': 10, 'Hygiene': 20, 'Structural': 15}}
{'BusinessName': 'A1 News & Wine',
 'scores': {'ConfidenceInManagement': 20, 'Hygiene': 20, 'Structural': 10}}
{'BusinessName': 'Cakes & Bakes',
 'scores': {'ConfidenceInManagement': 20, 'Hygiene': 20, 'Structural': 15}}
{'BusinessName': 'Sahajanand Catering Limited',
 'scores': {'ConfidenceInManagement': 5, 'Hygiene': 20, 'Structural': 20}}
{'BusinessName': 'Sisko Cafe',
 'scores': {'ConfidenceInManagement': 20, 'Hygiene': 20, 'Structural': 20}}
{'BusinessName': 'Magazin Romanesc Diana',
 'scores': {'ConfidenceInManagement': 20, 'Hygiene': 20, 'Structural': 10}}
{'BusinessName': 'Bali Maamalas',
 'scores': {'ConfidenceInManagement': 20, 'Hygiene': 20, 'Structural': 10}}
{'BusinessName': 'Angels Bakery',
 'scores': {'ConfidenceInManagement': 20, 'Hygiene': 20, 'Structural': 20}}
{'BusinessName': 'Nikkis Place Restaurant',
 'scores': {'ConfidenceInManagement': 20, 'Hygiene': 20, 'Structural': 20}}
{'BusinessName': 'Chicago 30',
 'scores': {'ConfidenceInManagement': 30, 'Hygiene': 20, 'Structural': 15}}
{'BusinessName': 'Samui Thai Restaurant',
 'scores': {'ConfidenceInManagement': 30, 'Hygiene': 20, 'Structural': 20}}
{'BusinessName': 'Pakhtoonkhwa Restaurant',
 'scores': {'ConfidenceInManagement': 20, 'Hygiene': 20, 'Structural': 20}}
{'BusinessName': 'New Happy Garden',
 'scores': {'ConfidenceInManagement': 20, 'Hygiene': 20, 'Structural': 20}}
{'BusinessName': 'Mummy Yum',
 'scores': {'ConfidenceInManagement': 20, 'Hygiene': 20, 'Structural': 20}}
{'BusinessName': 'Gospodina',
 'scores': {'ConfidenceInManagement': 30, 'Hygiene': 20, 'Structural': 20}}
{'BusinessName': "Leo's Bar & Grill",
 'scores': {'ConfidenceInManagement': 20, 'Hygiene': 20, 'Structural': 5}}
{'BusinessName': 'Royal Ribs',
 'scores': {'ConfidenceInManagement': 30, 'Hygiene': 20, 'Structural': 15}}
{'BusinessName': 'Great Hallingbury Manor Hotel',
 'scores': {'ConfidenceInManagement': 20, 'Hygiene': 20, 'Structural': 10}}
{'BusinessName': 'The Dog And Duck',
 'scores': {'ConfidenceInManagement': 20, 'Hygiene': 20, 'Structural': 15}}
{'BusinessName': 'Oriental Cottage',
 'scores': {'ConfidenceInManagement': 20, 'Hygiene': 20, 'Structural': 15}}

In [104]:
# Use count_documents to display the number of documents in the result
db.food.count_documents(query)
# Display the first document in the results using pprint
result = food.find_one(query)
pprint.pprint(result)

{'AddressLine1': '5-6 Southfields Road',
 'AddressLine2': 'Eastbourne',
 'AddressLine3': 'East Sussex',
 'AddressLine4': '',
 'BusinessName': 'The Chase Rest Home',
 'BusinessType': 'Caring Premises',
 'BusinessTypeID': 5,
 'ChangesByServerID': 0,
 'Distance': 4613.888288172291,
 'FHRSID': 110681,
 'LocalAuthorityBusinessID': '4029',
 'LocalAuthorityCode': '102',
 'LocalAuthorityEmailAddress': 'Customerfirst@eastbourne.gov.uk',
 'LocalAuthorityName': 'Eastbourne',
 'LocalAuthorityWebSite': 'http://www.eastbourne.gov.uk/foodratings',
 'NewRatingPending': False,
 'Phone': '',
 'PostCode': 'BN21 1BU',
 'RatingDate': '2021-09-23T00:00:00',
 'RatingKey': 'fhrs_0_en-gb',
 'RatingValue': 0,
 'RightToReply': '',
 'SchemeType': 'FHRS',
 '_id': ObjectId('6461011e1142c1728698b31f'),
 'geocode': {'latitude': Decimal128('50.769705'),
             'longitude': Decimal128('0.27694')},
 'latitude': None,
 'links': [{'href': 'https://api.ratings.food.gov.uk/establishments/110681',
            'rel': 'self'}],
 'longitude': None,
 'meta': {'dataSource': None,
          'extractDate': '0001-01-01T00:00:00',
          'itemCount': 0,
          'pageNumber': 0,
          'pageSize': 0,
          'returncode': None,
          'totalCount': 0,
          'totalPages': 0},
 'scores': {'ConfidenceInManagement': 20, 'Hygiene': 20, 'Structural': 20}}

In [105]:
import pandas as pd
# Convert the result to a Pandas DataFrame

result_df = pd.DataFrame(hygiene_list)

In [106]:
# Display the number of rows in the DataFrame
print(len(result_df))

41

In [107]:
# Display the first 10 rows of the DataFrame
result_df.head(10)

,BusinessName,scores
0,The Chase Rest Home,"{'Hygiene': 20, 'Structural': 20, 'ConfidenceI..."
1,Brenalwood,"{'Hygiene': 20, 'Structural': 15, 'ConfidenceI..."
2,Melrose Hotel,"{'Hygiene': 20, 'Structural': 20, 'ConfidenceI..."
3,Seaford Pizza,"{'Hygiene': 20, 'Structural': 10, 'ConfidenceI..."
4,Golden Palace,"{'Hygiene': 20, 'Structural': 10, 'ConfidenceI..."
5,Ashby's Butchers,"{'Hygiene': 20, 'Structural': 20, 'ConfidenceI..."
6,South Sea Express Cuisine,"{'Hygiene': 20, 'Structural': 20, 'ConfidenceI..."
7,Golden Palace,"{'Hygiene': 20, 'Structural': 15, 'ConfidenceI..."
8,The Tulip Tree,"{'Hygiene': 20, 'Structural': 5, 'ConfidenceIn..."
9,F & S,"{'Hygiene': 20, 'Structural': 20, 'ConfidenceI..."

### 2. Which establishments in London have a `RatingValue` greater than or equal to 4?

In [108]:
# Find the establishments with London as the Local Authority and has a RatingValue greater than or equal to 4.
query = {'RatingValue': {'$gt': 3}}

# Use count_documents to display the number of documents in the result
count = food.count_documents(query)
print("Number of documents in London with RatingValue >= 4:", count)
limit = 1

# Display the first document in the results using pprint
result = food.find(query).sort(sort).limit(limit)
for document in result:
    pprint.pprint(document)

Number of documents in London with RatingValue >= 4: 31257
{'AddressLine1': 'Folkestone Harbour',
 'AddressLine2': 'Harbour Approach Road',
 'AddressLine3': 'Folkestone',
 'AddressLine4': 'Kent',
 'BusinessName': "Dino's",
 'BusinessType': 'Restaurant/Cafe/Canteen',
 'BusinessTypeID': 1,
 'ChangesByServerID': 0,
 'Distance': 4591.914705329384,
 'FHRSID': 1396944,
 'LocalAuthorityBusinessID': 'PI/000078122',
 'LocalAuthorityCode': '188',
 'LocalAuthorityEmailAddress': 'foodteam@folkestone-hythe.gov.uk',
 'LocalAuthorityName': 'Folkestone and Hythe',
 'LocalAuthorityWebSite': 'http://www.folkestone-hythe.gov.uk',
 'NewRatingPending': False,
 'Phone': '',
 'PostCode': '',
 'RatingDate': '2021-06-06T00:00:00',
 'RatingKey': 'fhrs_4_en-gb',
 'RatingValue': 4,
 'RightToReply': '',
 'SchemeType': 'FHRS',
 '_id': ObjectId('6461011e1142c172869897fb'),
 'geocode': {'latitude': Decimal128('51.0783519967076'),
             'longitude': Decimal128('1.18590330311705')},
 'latitude': None,
 'links': [{'href': 'https://api.ratings.food.gov.uk/establishments/1396944',
            'rel': 'self'}],
 'longitude': None,
 'meta': {'dataSource': None,
          'extractDate': '0001-01-01T00:00:00',
          'itemCount': 0,
          'pageNumber': 0,
          'pageSize': 0,
          'returncode': None,
          'totalCount': 0,
          'totalPages': 0},
 'scores': {'ConfidenceInManagement': 5, 'Hygiene': 10, 'Structural': 5}}

In [109]:
# Convert the result to a Pandas DataFrame
result = food.find(query).sort(sort)
result_dict = []
for document in result:
    result_dict.append(document)
result_df = pd.DataFrame(result_dict)

# Display the number of rows in the DataFrame
print(len(result_df))

# Display the first 10 rows of the DataFrame
result_df.head(10)

31257

,_id,FHRSID,ChangesByServerID,LocalAuthorityBusinessID,BusinessName,BusinessType,BusinessTypeID,AddressLine1,AddressLine2,AddressLine3,...,scores,SchemeType,geocode,RightToReply,Distance,NewRatingPending,meta,links,longitude,latitude
0,6461011e1142c172869897fb,1396944,0,PI/000078122,Dino's,Restaurant/Cafe/Canteen,1,Folkestone Harbour,Harbour Approach Road,Folkestone,...,"{'Hygiene': 10, 'Structural': 5, 'ConfidenceIn...",FHRS,"{'longitude': 1.18590330311705, 'latitude': 51...",,4591.914705,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'https://api.ratings....",None,None
1,6461011e1142c17286989839,1241756,0,PI/000077659,Tips Wok Box,Takeaway/sandwich shop,7844,Ground Floor Business Premises,4 Tontine Street,Folkestone,...,"{'Hygiene': 10, 'Structural': 0, 'ConfidenceIn...",FHRS,"{'longitude': 1.18431901931763, 'latitude': 51...",,4592.069893,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'https://api.ratings....",None,None
2,6461011e1142c17286989850,990687,0,PI/000075113,The Folkestone Wine Company,Other catering premises,7841,Ground Floor Business Premises,5 Church Street,Folkestone,...,"{'Hygiene': 10, 'Structural': 5, 'ConfidenceIn...",FHRS,"{'longitude': 1.181365, 'latitude': 51.079542}",,4592.124762,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'https://api.ratings....",None,None
3,6461011e1142c17286989873,534010,0,PI/000029249,Wetherspoons,Pub/bar/nightclub,7843,The Samuel Peto,23 Rendezvous Street,Folkestone,...,"{'Hygiene': 10, 'Structural': 10, 'ConfidenceI...",FHRS,"{'longitude': 1.181282, 'latitude': 51.080417}",,4592.160633,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'https://api.ratings....",None,None
4,6461011e1142c1728698987b,738472,0,PI/000072576,Kathmandu House Grilled Tandoori,Restaurant/Cafe/Canteen,1,13-15 West Terrace,Folkestone,Kent,...,"{'Hygiene': 10, 'Structural': 10, 'ConfidenceI...",FHRS,"{'longitude': 1.178909, 'latitude': 51.078296}",,4592.167495,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'https://api.ratings....",None,None
5,6461011e1142c1728698988b,1210205,0,PI/000077248,Lilys American Diner,Restaurant/Cafe/Canteen,1,Ground Floor Business Premises,71 Sandgate Road,Folkestone,...,"{'Hygiene': 10, 'Structural': 0, 'ConfidenceIn...",FHRS,"{'longitude': 1.178027, 'latitude': 51.078131}",,4592.193445,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'https://api.ratings....",None,None
6,6461011e1142c172869898bf,565884,0,PI/000070802,Cafe Tulip,Restaurant/Cafe/Canteen,1,Ground Floor Business Premises,3 Shellons Street,Folkestone,...,"{'Hygiene': 10, 'Structural': 5, 'ConfidenceIn...",FHRS,"{'longitude': 1.178969, 'latitude': 51.080624}",,4592.252693,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'https://api.ratings....",None,None
7,6461011e1142c172869898c2,987214,0,PI/000075687,Papa Johns Pizza,Takeaway/sandwich shop,7844,Ground Floor Business Premises,115 Sandgate Road,Folkestone,...,"{'Hygiene': 10, 'Structural': 0, 'ConfidenceIn...",FHRS,"{'longitude': 1.17575, 'latitude': 51.077626}",,4592.257476,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'https://api.ratings....",None,None
8,6461011e1142c172869898ce,577171,0,PI/000030039,Bella Pizza & Pasta,Restaurant/Cafe/Canteen,1,124 Sandgate Road,Folkestone,Kent,...,"{'Hygiene': 10, 'Structural': 5, 'ConfidenceIn...",FHRS,"{'longitude': 1.17535, 'latitude': 51.078033}",,4592.287331,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'https://api.ratings....",None,None
9,6461011e1142c172869898d7,751315,0,PI/000041442,Folkestone Baptist Church,Other catering premises,7841,Hill Road,Folkestone,Kent,...,"{'Hygiene': 10, 'Structural': 0, 'ConfidenceIn...",FHRS,"{'longitude': 1.189833, 'latitude': 51.09221}",,4592.291857,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'https://api.ratings....",None,None

### 3. What are the top 5 establishments with a `RatingValue` rating value of 5, sorted by lowest hygiene score, nearest to the new restaurant added, "Penang Flavours"?

In [110]:
# Search within 0.01 degree on either side of the latitude and longitude.
# Rating value must equal 5
# Sort by hygiene score

degree_search = 0.01
latitude = 51.49014200
longitude = 0.08384000

query = {
    'geocode.longitude': {'$gte': longitude - degree_search, '$lte': longitude + degree_search},
    'geocode.latitude': {'$gte': latitude - degree_search, '$lte': latitude + degree_search},
    'RatingValue': 5
}

sort = [('scores.Hygiene', -1)]
limit = 5

# Retrieve the matching documents and sort by hygiene score
results = food.find(query).sort(sort).limit(limit)
results_dict = []

# Iterate over the results and print each document
for document in results:
    pprint.pprint(document)
    results_dict.append(document)

{'AddressLine1': '101 Plumstead High Street',
 'AddressLine2': '',
 'AddressLine3': 'Plumstead',
 'AddressLine4': 'Greenwich',
 'BusinessName': 'Lucky Food & Wine',
 'BusinessType': 'Retailers - other',
 'BusinessTypeID': 4613,
 'ChangesByServerID': 0,
 'Distance': 4647.024793263386,
 'FHRSID': 695287,
 'LocalAuthorityBusinessID': 'PI/000182135',
 'LocalAuthorityCode': '511',
 'LocalAuthorityEmailAddress': 'health@royalgreenwich.gov.uk',
 'LocalAuthorityName': 'Greenwich',
 'LocalAuthorityWebSite': 'http://www.royalgreenwich.gov.uk',
 'NewRatingPending': False,
 'Phone': '',
 'PostCode': 'SE18 1SB',
 'RatingDate': '2022-06-25T00:00:00',
 'RatingKey': 'fhrs_5_en-gb',
 'RatingValue': 5,
 'RightToReply': '',
 'SchemeType': 'FHRS',
 '_id': ObjectId('646101201142c17286990c16'),
 'geocode': {'latitude': Decimal128('51.4878934'),
             'longitude': Decimal128('0.0910104')},
 'latitude': None,
 'links': [{'href': 'http://api.ratings.food.gov.uk/establishments/695287',
            'rel': 'self'}],
 'longitude': None,
 'meta': {'dataSource': None,
          'extractDate': '0001-01-01T00:00:00',
          'itemCount': 0,
          'pageNumber': 0,
          'pageSize': 0,
          'returncode': None,
          'totalCount': 0,
          'totalPages': 0},
 'scores': {'ConfidenceInManagement': 5, 'Hygiene': 5, 'Structural': 5}}
{'AddressLine1': '112 Plumstead High Street',
 'AddressLine2': '',
 'AddressLine3': 'Plumstead',
 'AddressLine4': 'Greenwich',
 'BusinessName': 'Fineway Cash & Carry',
 'BusinessType': 'Retailers - other',
 'BusinessTypeID': 4613,
 'ChangesByServerID': 0,
 'Distance': 4647.016995291011,
 'FHRSID': 694606,
 'LocalAuthorityBusinessID': 'PI/000116584',
 'LocalAuthorityCode': '511',
 'LocalAuthorityEmailAddress': 'health@royalgreenwich.gov.uk',
 'LocalAuthorityName': 'Greenwich',
 'LocalAuthorityWebSite': 'http://www.royalgreenwich.gov.uk',
 'NewRatingPending': False,
 'Phone': '',
 'PostCode': 'SE18 1SJ',
 'RatingDate': '2020-10-20T00:00:00',
 'RatingKey': 'fhrs_5_en-gb',
 'RatingValue': 5,
 'RightToReply': '',
 'SchemeType': 'FHRS',
 '_id': ObjectId('646101201142c17286990c04'),
 'geocode': {'latitude': Decimal128('51.4876089'),
             'longitude': Decimal128('0.0909382')},
 'latitude': None,
 'links': [{'href': 'http://api.ratings.food.gov.uk/establishments/694606',
            'rel': 'self'}],
 'longitude': None,
 'meta': {'dataSource': None,
          'extractDate': '0001-01-01T00:00:00',
          'itemCount': 0,
          'pageNumber': 0,
          'pageSize': 0,
          'returncode': None,
          'totalCount': 0,
          'totalPages': 0},
 'scores': {'ConfidenceInManagement': 5, 'Hygiene': 5, 'Structural': 5}}
{'AddressLine1': '104 Plumstead High Street',
 'AddressLine2': '',
 'AddressLine3': 'Plumstead',
 'AddressLine4': 'Greenwich',
 'BusinessName': 'Everest Stores Ltd',
 'BusinessType': 'Retailers - other',
 'BusinessTypeID': 4613,
 'ChangesByServerID': 0,
 'Distance': 4647.041728368117,
 'FHRSID': 695033,
 'LocalAuthorityBusinessID': 'PI/000172986',
 'LocalAuthorityCode': '511',
 'LocalAuthorityEmailAddress': 'health@royalgreenwich.gov.uk',
 'LocalAuthorityName': 'Greenwich',
 'LocalAuthorityWebSite': 'http://www.royalgreenwich.gov.uk',
 'NewRatingPending': False,
 'Phone': '',
 'PostCode': 'SE18 1SJ',
 'RatingDate': '2021-09-13T00:00:00',
 'RatingKey': 'fhrs_5_en-gb',
 'RatingValue': 5,
 'RightToReply': '',
 'SchemeType': 'FHRS',
 '_id': ObjectId('646101201142c17286990c3a'),
 'geocode': {'latitude': Decimal128('51.4876718'),
             'longitude': Decimal128('0.0903232')},
 'latitude': None,
 'links': [{'href': 'http://api.ratings.food.gov.uk/establishments/695033',
            'rel': 'self'}],
 'longitude': None,
 'meta': {'dataSource': None,
          'extractDate': '0001-01-01T00:00:00',
          'itemCount': 0,
          'pageNumber': 0,
          'pageSize': 0,
          'returncode': None,
          'totalCount': 0,
          'totalPages': 0},
 'scores': {'ConfidenceInManagement': 5, 'Hygiene': 5, 'Structural': 5}}
{'AddressLine1': '102 Plumstead High Street',
 'AddressLine2': '',
 'AddressLine3': 'Plumstead',
 'AddressLine4': 'Greenwich',
 'BusinessName': 'Premier Express',
 'BusinessType': 'Retailers - other',
 'BusinessTypeID': 4613,
 'ChangesByServerID': 0,
 'Distance': 4647.038806595731,
 'FHRSID': 695566,
 'LocalAuthorityBusinessID': 'PI/000188497',
 'LocalAuthorityCode': '511',
 'LocalAuthorityEmailAddress': 'health@royalgreenwich.gov.uk',
 'LocalAuthorityName': 'Greenwich',
 'LocalAuthorityWebSite': 'http://www.royalgreenwich.gov.uk',
 'NewRatingPending': False,
 'Phone': '',
 'PostCode': 'SE18 1SJ',
 'RatingDate': '2021-06-10T00:00:00',
 'RatingKey': 'fhrs_5_en-gb',
 'RatingValue': 5,
 'RightToReply': '',
 'SchemeType': 'FHRS',
 '_id': ObjectId('646101201142c17286990c33'),
 'geocode': {'latitude': Decimal128('51.4877234'),
             'longitude': Decimal128('0.0904552')},
 'latitude': None,
 'links': [{'href': 'http://api.ratings.food.gov.uk/establishments/695566',
            'rel': 'self'}],
 'longitude': None,
 'meta': {'dataSource': None,
          'extractDate': '0001-01-01T00:00:00',
          'itemCount': 0,
          'pageNumber': 0,
          'pageSize': 0,
          'returncode': None,
          'totalCount': 0,
          'totalPages': 0},
 'scores': {'ConfidenceInManagement': 0, 'Hygiene': 5, 'Structural': 0}}
{'AddressLine1': '152 Plumstead High Street',
 'AddressLine2': '',
 'AddressLine3': 'Plumstead',
 'AddressLine4': 'Greenwich',
 'BusinessName': 'TIWA N TIWA African Restaurant Ltd',
 'BusinessType': 'Restaurant/Cafe/Canteen',
 'BusinessTypeID': 1,
 'ChangesByServerID': 0,
 'Distance': 4646.930146257832,
 'FHRSID': 1069652,
 'LocalAuthorityBusinessID': 'PI/000206841',
 'LocalAuthorityCode': '511',
 'LocalAuthorityEmailAddress': 'health@royalgreenwich.gov.uk',
 'LocalAuthorityName': 'Greenwich',
 'LocalAuthorityWebSite': 'http://www.royalgreenwich.gov.uk',
 'NewRatingPending': False,
 'Phone': '',
 'PostCode': 'SE18 1JQ',
 'RatingDate': '2020-10-24T00:00:00',
 'RatingKey': 'fhrs_5_en-gb',
 'RatingValue': 5,
 'RightToReply': '',
 'SchemeType': 'FHRS',
 '_id': ObjectId('646101201142c17286990b25'),
 'geocode': {'latitude': Decimal128('51.4870351'),
             'longitude': Decimal128('0.0927429')},
 'latitude': None,
 'links': [{'href': 'http://api.ratings.food.gov.uk/establishments/1069652',
            'rel': 'self'}],
 'longitude': None,
 'meta': {'dataSource': None,
          'extractDate': '0001-01-01T00:00:00',
          'itemCount': 0,
          'pageNumber': 0,
          'pageSize': 0,
          'returncode': None,
          'totalCount': 0,
          'totalPages': 0},
 'scores': {'ConfidenceInManagement': 5, 'Hygiene': 5, 'Structural': 5}}

In [111]:
# Convert result to Pandas DataFrame
result_df = pd.DataFrame(results_dict)
result_df.head()

,_id,FHRSID,ChangesByServerID,LocalAuthorityBusinessID,BusinessName,BusinessType,BusinessTypeID,AddressLine1,AddressLine2,AddressLine3,...,scores,SchemeType,geocode,RightToReply,Distance,NewRatingPending,meta,links,longitude,latitude
0,646101201142c17286990c16,695287,0,PI/000182135,Lucky Food & Wine,Retailers - other,4613,101 Plumstead High Street,,Plumstead,...,"{'Hygiene': 5, 'Structural': 5, 'ConfidenceInM...",FHRS,"{'longitude': 0.0910104, 'latitude': 51.4878934}",,4647.024793,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'http://api.ratings.f...",None,None
1,646101201142c17286990c04,694606,0,PI/000116584,Fineway Cash & Carry,Retailers - other,4613,112 Plumstead High Street,,Plumstead,...,"{'Hygiene': 5, 'Structural': 5, 'ConfidenceInM...",FHRS,"{'longitude': 0.0909382, 'latitude': 51.4876089}",,4647.016995,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'http://api.ratings.f...",None,None
2,646101201142c17286990c3a,695033,0,PI/000172986,Everest Stores Ltd,Retailers - other,4613,104 Plumstead High Street,,Plumstead,...,"{'Hygiene': 5, 'Structural': 5, 'ConfidenceInM...",FHRS,"{'longitude': 0.0903232, 'latitude': 51.4876718}",,4647.041728,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'http://api.ratings.f...",None,None
3,646101201142c17286990c33,695566,0,PI/000188497,Premier Express,Retailers - other,4613,102 Plumstead High Street,,Plumstead,...,"{'Hygiene': 5, 'Structural': 0, 'ConfidenceInM...",FHRS,"{'longitude': 0.0904552, 'latitude': 51.4877234}",,4647.038807,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'http://api.ratings.f...",None,None
4,646101201142c17286990b25,1069652,0,PI/000206841,TIWA N TIWA African Restaurant Ltd,Restaurant/Cafe/Canteen,1,152 Plumstead High Street,,Plumstead,...,"{'Hygiene': 5, 'Structural': 5, 'ConfidenceInM...",FHRS,"{'longitude': 0.0927429, 'latitude': 51.4870351}",,4646.930146,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'http://api.ratings.f...",None,None

### 4. How many establishments in each Local Authority area have a hygiene score of 0?

In [112]:
# Create a pipeline that: 
# 1. Matches establishments with a hygiene score of 0
# 2. Groups the matches by Local Authority
# 3. Sorts the matches from highest to lowest

match_query = {'$match': {'scores.Hygiene': 0}}
group_query = {'$group': {'_id': '$LocalAuthorityName', 'count': {'$sum': 1}}}
sort = {'$sort': {'count': -1}}

# Combine the pipeline stages
pipeline = [match_query, group_query, sort]

# Execute the pipeline
results = list(food.aggregate(pipeline))

# Print the number of documents in the result
print("Number of documents:", len(results))

# Print the first 10 results
pprint.pprint(results[:10])

Number of documents: 55
[{'_id': 'Thanet', 'count': 1130},
 {'_id': 'Greenwich', 'count': 882},
 {'_id': 'Maidstone', 'count': 713},
 {'_id': 'Newham', 'count': 711},
 {'_id': 'Swale', 'count': 686},
 {'_id': 'Chelmsford', 'count': 680},
 {'_id': 'Medway', 'count': 672},
 {'_id': 'Bexley', 'count': 607},
 {'_id': 'Southend-On-Sea', 'count': 586},
 {'_id': 'Tendring', 'count': 542}]

In [118]:
# Convert the result to a Pandas DataFrame
result_dict = []
for document in results:
    results_dict.append(document)
result_df = pd.DataFrame(results_dict)
result_df = result_df[['_id', 'count']]
result_df = result_df.drop(result_df.index[:5])
result_df.reset_index(inplace=True)
result_df = result_df.drop('index', axis=1)
print(len(result_df))
# Display the first 10 rows of the DataFrame
result_df.head(10)

330

               _id   count
0           Thanet  1130.0
1        Greenwich   882.0
2        Maidstone   713.0
3           Newham   711.0
4            Swale   686.0
5       Chelmsford   680.0
6           Medway   672.0
7           Bexley   607.0
8  Southend-On-Sea   586.0
9         Tendring   542.0